name = input("Enter your name: ")
branch = input("Enter your branch: ")
gender = input("Enter your gender: ")
college = input("Enter your college: ")
age = input("Enter your age: ")

print("\nNAME: ", name)
print("BRANCH: ", branch)
print("GENDER: ",gender)
print("COLLEGE: ",college)
print("AGE: ",age)
